### ISSUE TITLE
pkg-config: obsolete

### ISSUE THREAD

**Issue by jimlynnjulian** [zhiayang/mkvtaginator#2]
pkg-config is considered obsolete. A suitable replacement may be pkgconf.
"https://github.com/pkgconf/pkgconf"

**Comment by zhiayang** [comment]
AFAIK, `pkgconf` installs a `pkg-config` symlink, but obviously `pkg-config` does not have a symlink to `pkgconf`. Keeping `pkg-config` means it will work on systems that use both.
